"""FastAPI application.

The API is a thin wrapper over :mod:`qra.tools` and the workspace service —
deliberately thin, so the MCP server, the agents and the HTTP clients cannot
drift apart in behaviour.
"""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from qra.api.routers import analytics, corpus, export, meta, research, search, workspace

app = FastAPI(
    title="Quran Research Agent",
    version="0.1.0",
    description=(
        "Deterministic retrieval, pattern mining and agentic research over a closed, "
        "fully-structured corpus. Retrieval modes are exposed separately and labelled: "
        "deterministic results are exhaustive, ranked results are not."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(corpus.router)
app.include_router(search.router)
app.include_router(analytics.router)
app.include_router(workspace.router)
app.include_router(export.router)
app.include_router(research.router)
app.include_router(meta.router)


@app.get("/", tags=["meta"])
def root() -> dict:
    return {
        "name": "Quran Research Agent",
        "docs": "/docs",
        "principles": [
            "Retrieval is deterministic and exhaustive where it claims to be.",
            "Arabic text, translations and hadith matn are rendered from the database by id, "
            "never generated by a model.",
            "Every count is reported with what it would have been by chance.",
            "Violations are shown before supporting evidence.",
        ],
    }
