"""FastAPI application.

The API is a thin wrapper over :mod:`qra.tools` and the workspace service —
deliberately thin, so the MCP server, the agents and the HTTP clients cannot
drift apart in behaviour.
"""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from qra import ops
from qra.api.routers import (
    analytics,
    auth,
    corpus,
    export,
    meta,
    research,
    search,
    workspace,
)
from qra.config import settings

app = FastAPI(
    title="Quran Research Agent",
    version="0.1.0",
    description=(
        "Deterministic retrieval, pattern mining and agentic research over a closed, "
        "fully-structured corpus. Retrieval modes are exposed separately and labelled: "
        "deterministic results are exhaustive, ranked results are not."
    ),
)

ops.configure_logging()
ops.install(app)

# The frontend is always a different origin from the API (3000 vs 8000 in
# development, usually different hosts in production), so CORS is load-bearing
# rather than incidental.
#
# `allow_origins=["*"]` together with `allow_credentials=True` is the trap here:
# the CORS spec forbids that combination, so Starlette silently omits the header
# and *every* cross-origin request fails. Auth travels as a Bearer header, not a
# cookie, so credentials are not needed — a wildcard without them is both legal
# and sufficient. Naming origins in QRA_CORS_ORIGINS switches on the stricter
# mode, which is what a shared deployment should do.
_origins = settings.cors_origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins or ["*"],
    allow_credentials=bool(_origins),
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(corpus.router)
app.include_router(search.router)
app.include_router(analytics.router)
app.include_router(workspace.router)
app.include_router(export.router)
app.include_router(research.router)
app.include_router(meta.router)


@app.get("/", tags=["meta"])
def root() -> dict:
    return {
        "name": "Quran Research Agent",
        "docs": "/docs",
        "principles": [
            "Retrieval is deterministic and exhaustive where it claims to be.",
            "Arabic text, translations and hadith matn are rendered from the database by id, "
            "never generated by a model.",
            "Every count is reported with what it would have been by chance.",
            "Violations are shown before supporting evidence.",
        ],
    }
