"""The export document model.

One structure that every exporter renders, so a finding looks the same in Word,
in a deck and on paper, and so the things that must not be lost — citations,
provenance tags, the chance baseline next to a count — are carried structurally
rather than re-derived by each format.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Literal

from sqlalchemy import select
from sqlalchemy.orm import Session

from qra.export.citations import Bibliography, collect, licence_notice
from qra.models import Finding, Hypothesis, HypothesisRun, Note, ResearchRun

BlockKind = Literal["heading", "text", "ayah", "translation", "quote", "stat", "list", "table", "note"]
Provenance = Literal["retrieved", "system_suggested", "own_note"]


@dataclass
class Block:
    kind: BlockKind
    text: str = ""
    # Every block declares where it came from. The three states are visually
    # distinct in every output format, not just on screen.
    provenance: Provenance = "retrieved"
    ref: str | None = None
    language: str = "en"
    rtl: bool = False
    level: int = 2
    items: list[str] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)
    citation: dict | None = None
    meta: dict = field(default_factory=dict)


@dataclass
class Document:
    title: str
    subtitle: str = ""
    language: str = "en"
    blocks: list[Block] = field(default_factory=list)
    citations: list[dict] = field(default_factory=list)
    licence: str = ""
    generated_at: str = field(default_factory=lambda: datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"))

    @property
    def rtl(self) -> bool:
        return self.language in ("ur", "ar")

    def bibliography(self) -> Bibliography:
        return collect(self.citations, language=self.language)

    def add(self, block: Block) -> None:
        self.blocks.append(block)


PROVENANCE_LABEL = {
    "en": {
        "retrieved": "retrieved",
        "system_suggested": "system-suggested",
        "own_note": "researcher's note",
    },
    "ur": {
        "retrieved": "ماخوذ",
        "system_suggested": "نظام کی تجویز",
        "own_note": "محقق کا نوٹ",
    },
}

STRINGS = {
    "en": {
        "generated": "Generated",
        "verdict": "Verdict",
        "violations": "Violating cases",
        "supporting": "Supporting cases",
        "coverage": "Coverage",
        "baseline": "Chance baseline",
        "statistics": "Statistics",
        "open_questions": "Open questions",
        "disagreement": "Where the commentators disagree",
        "provenance_key": "Provenance key",
        "no_generated_scripture": (
            "Every ayah, translation and hadith in this document was rendered from the "
            "database by reference. No scripture here was generated by a model."
        ),
    },
    "ur": {
        "generated": "تیار شدہ",
        "verdict": "فیصلہ",
        "violations": "مخالف شواہد",
        "supporting": "موافق شواہد",
        "coverage": "احاطہ",
        "baseline": "اتفاقی بنیاد",
        "statistics": "اعداد و شمار",
        "open_questions": "کھلے سوالات",
        "disagreement": "مفسرین کا اختلاف",
        "provenance_key": "ماخذ کی علامات",
        "no_generated_scripture": (
            "اس دستاویز میں ہر آیت، ترجمہ اور حدیث براہِ راست ڈیٹا بیس سے پیش کی گئی ہے۔ "
            "کوئی متن ماڈل نے تخلیق نہیں کیا۔"
        ),
    },
}


def _strings(language: str) -> dict:
    return STRINGS.get(language, STRINGS["en"])


def _footer_blocks(document: Document, session: Session) -> None:
    strings = _strings(document.language)
    labels = PROVENANCE_LABEL.get(document.language, PROVENANCE_LABEL["en"])
    document.add(Block(kind="heading", text=strings["provenance_key"], level=2))
    document.add(
        Block(
            kind="list",
            items=[
                f"{labels['retrieved']} — from a cited source in the corpus",
                f"{labels['system_suggested']} — computed or proposed by the system",
                f"{labels['own_note']} — written by the researcher",
            ],
            provenance="system_suggested",
        )
    )
    bibliography = document.bibliography()
    if bibliography.entries:
        document.add(Block(kind="heading", text=bibliography.labels["sources"], level=2))
        document.add(Block(kind="list", items=bibliography.lines(), provenance="retrieved"))
        document.licence = licence_notice(session, bibliography.entries, language=document.language)
    document.add(Block(kind="text", text=strings["no_generated_scripture"], provenance="system_suggested"))


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------


def from_research_run(session: Session, run_id: str, *, language: str | None = None) -> Document:
    """Render an agent run: the Critic's report first, then the draft."""
    run = session.get(ResearchRun, run_id)
    if run is None:
        raise ValueError(f"run {run_id} not found")
    ledger = run.ledger or {}
    language = language or run.language
    strings = _strings(language)

    document = Document(title=run.question, subtitle=f"run {run.id}", language=language)
    rtl = language in ("ur", "ar")

    critic = ledger.get("critic_report") or {}
    if critic:
        document.add(Block(kind="heading", text=f"Critic: {critic.get('verdict', '—')}", level=2))
        document.add(
            Block(
                kind="list",
                provenance="system_suggested",
                items=[
                    f"{critic.get('citations_checked', 0)} citations re-resolved against the database",
                    f"{len(critic.get('citations_failed', []))} citations failed to resolve",
                    f"{critic.get('counter_examples_found', 0)} counter-examples found",
                    f"{len(critic.get('scripture_violations', []))} un-cited Arabic runs in the draft",
                ],
            )
        )

    from qra.agents.render import render

    rendered = render(session, run.output or "", strict=False)
    document.citations = rendered.citations
    for paragraph in [p for p in rendered.text.split("\n") if p.strip()]:
        if paragraph.startswith("#"):
            level = len(paragraph) - len(paragraph.lstrip("#"))
            document.add(Block(kind="heading", text=paragraph.lstrip("# "), level=max(2, level)))
        else:
            document.add(
                Block(kind="text", text=paragraph.lstrip("- "), language=language, rtl=rtl)
            )

    for item in ledger.get("disagreements", []):
        document.add(Block(kind="heading", text=f"{strings['disagreement']}: {item['topic']}", level=3))
        for position in item.get("positions", []):
            died = f" (d. {position['died_ah']} AH)" if position.get("died_ah") else ""
            document.add(
                Block(
                    kind="quote",
                    text=f"{position.get('author', '')}{died}: {position.get('excerpt', '')[:600]}",
                    language="ar",
                    rtl=True,
                    citation=position.get("citation"),
                )
            )
            if position.get("citation"):
                document.citations.append(position["citation"])

    if ledger.get("open_questions"):
        document.add(Block(kind="heading", text=strings["open_questions"], level=2))
        document.add(
            Block(kind="list", items=ledger["open_questions"], provenance="system_suggested")
        )

    _footer_blocks(document, session)
    return document


def from_hypothesis(session: Session, hypothesis_id: int, *, language: str | None = None) -> Document:
    """Render a hypothesis and its latest run — violations first, as everywhere."""
    row = session.get(Hypothesis, hypothesis_id)
    if row is None:
        raise ValueError(f"hypothesis {hypothesis_id} not found")
    language = language or row.language
    strings = _strings(language)
    latest = session.scalars(
        select(HypothesisRun)
        .where(HypothesisRun.hypothesis_id == row.id)
        .order_by(HypothesisRun.created_at.desc())
    ).first()

    document = Document(title=row.title, subtitle=row.statement, language=language)
    document.add(
        Block(kind="text", text=row.statement, language=language, rtl=language in ("ur", "ar"))
    )

    if latest is None:
        document.add(Block(kind="text", text="Not yet tested.", provenance="system_suggested"))
        _footer_blocks(document, session)
        return document

    statistics = latest.statistics or {}
    document.add(Block(kind="heading", text=strings["verdict"], level=2))
    document.add(Block(kind="text", text=latest.verdict.replace("_", " "), provenance="system_suggested"))
    document.add(
        Block(
            kind="stat",
            provenance="system_suggested",
            rows=[
                [strings["violations"], str(len(latest.violating))],
                [strings["supporting"], str(len(latest.supporting))],
                [strings["coverage"], f"{latest.coverage * 100:.1f}%"],
                [strings["baseline"], f"{float(statistics.get('baseline_rate', 0)) * 100:.1f}%"],
            ],
        )
    )
    if statistics.get("interpretation"):
        document.add(
            Block(kind="text", text=statistics["interpretation"], provenance="system_suggested")
        )
    if statistics.get("null_model"):
        document.add(
            Block(
                kind="text",
                text=f"Null model: {statistics['null_model']}",
                provenance="system_suggested",
            )
        )

    # Violations before support. The ordering is the product, not a preference.
    for label, ayah_ids in (
        (strings["violations"], latest.violating),
        (strings["supporting"], latest.supporting),
    ):
        document.add(Block(kind="heading", text=f"{label} ({len(ayah_ids)})", level=2))
        for span, citation in _ayah_blocks(session, ayah_ids[:40]):
            document.add(span)
            document.citations.append(citation)

    _footer_blocks(document, session)
    return document


def from_notes(session: Session, note_ids: list[int], *, language: str = "en", title: str = "Notes") -> Document:
    document = Document(title=title, language=language)
    for note_id in note_ids:
        note = session.get(Note, note_id)
        if note is None:
            continue
        document.add(Block(kind="heading", text=note.title, level=2))
        document.add(
            Block(
                kind="note",
                text=note.body,
                provenance=note.provenance,
                language=note.language,
                rtl=note.language in ("ur", "ar"),
            )
        )
        anchor_ids = [a.ayah_id for a in note.anchors if a.ayah_id]
        for span, citation in _ayah_blocks(session, anchor_ids):
            document.add(span)
            document.citations.append(citation)
    _footer_blocks(document, session)
    return document


def from_finding(session: Session, finding_id: int, *, language: str | None = None) -> Document:
    finding = session.get(Finding, finding_id)
    if finding is None:
        raise ValueError(f"finding {finding_id} not found")
    language = language or finding.language
    document = Document(title=finding.question, language=language)
    document.add(
        Block(
            kind="text",
            text=finding.summary,
            language=language,
            rtl=language in ("ur", "ar"),
            provenance="retrieved" if finding.review_status == "approved" else "system_suggested",
        )
    )
    if finding.review_status != "approved":
        document.add(
            Block(
                kind="text",
                text=f"Review status: {finding.review_status} — not signed off by a reviewer.",
                provenance="system_suggested",
            )
        )
    document.citations = list(finding.citations or [])
    _footer_blocks(document, session)
    return document


def _ayah_blocks(session: Session, ayah_ids: list[int]):
    """Ayah blocks rendered from the database — never from a caller's string."""
    from qra.citations import ayah_citation
    from qra.models import Ayah

    for ayah_id in ayah_ids:
        ayah = session.get(Ayah, ayah_id)
        if ayah is None:
            continue
        citation = ayah_citation(ayah).to_dict()
        yield (
            Block(
                kind="ayah",
                text=ayah.text_uthmani,
                ref=f"{ayah.surah_id}:{ayah.ayah_num}",
                language="ar",
                rtl=True,
                provenance="retrieved",
                citation=citation,
            ),
            citation,
        )
