"""initial schema

Revision ID: 1f6436e40851
Revises: 
Create Date: 2026-08-20 19:16:47.464564
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1f6436e40851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entry',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cache_entry_kind'), 'cache_entry', ['kind'], unique=False)
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('label_ar', sa.String(length=128), nullable=True),
    sa.Column('label_ur', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_slug'), 'concept', ['slug'], unique=True)
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=False),
    sa.Column('license_status', sa.String(length=16), nullable=False),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('death_year_hijri', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=16), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edition_kind'), 'edition', ['kind'], unique=False)
    op.create_index(op.f('ix_edition_language'), 'edition', ['language'], unique=False)
    op.create_index(op.f('ix_edition_license_status'), 'edition', ['license_status'], unique=False)
    op.create_index(op.f('ix_edition_slug'), 'edition', ['slug'], unique=True)
    op.create_table('ingest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_log_step'), 'ingest_log', ['step'], unique=False)
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('privacy_mode', sa.String(length=16), nullable=False),
    sa.Column('model_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("privacy_mode in ('standard','local_only')", name='ck_org_privacy'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_slug'), 'organisation', ['slug'], unique=True)
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_start', sa.Integer(), nullable=False),
    sa.Column('ayah_end', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passage_surah_id'), 'passage', ['surah_id'], unique=False)
    op.create_table('root',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root', sa.String(length=32), nullable=False),
    sa.Column('root_display', sa.String(length=32), nullable=False),
    sa.Column('letters', sa.Integer(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_root'), 'root', ['root'], unique=True)
    op.create_table('search_term',
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('df', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('term')
    )
    op.create_table('surah',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_translit', sa.String(length=128), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.Column('revelation_place', sa.String(length=8), nullable=False),
    sa.Column('revelation_order', sa.Integer(), nullable=False),
    sa.Column('revelation_order_scheme', sa.String(length=32), nullable=False),
    sa.Column('has_bismillah', sa.Boolean(), nullable=False),
    sa.CheckConstraint("revelation_place in ('makki','madani')", name='ck_surah_place'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surah_revelation_order'), 'surah', ['revelation_order'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('oidc_subject', sa.String(length=256), nullable=True),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('reader','researcher','reviewer','admin')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_app_user_oidc_subject'), 'app_user', ['oidc_subject'], unique=False)
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_table('ayah',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_num', sa.Integer(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.Column('text_imlaei', sa.Text(), nullable=False),
    sa.Column('text_search', sa.Text(), nullable=False),
    sa.Column('text_loose', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('letter_count', sa.Integer(), nullable=False),
    sa.Column('revelation_place', sa.String(length=8), nullable=False),
    sa.Column('revelation_order', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('hizb', sa.Integer(), nullable=True),
    sa.Column('manzil', sa.Integer(), nullable=True),
    sa.Column('ruku', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('sajda', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['surah_id'], ['surah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surah_id', 'ayah_num', name='uq_ayah_ref')
    )
    op.create_index(op.f('ix_ayah_juz'), 'ayah', ['juz'], unique=False)
    op.create_index('ix_ayah_loose', 'ayah', ['text_loose'], unique=False)
    op.create_index(op.f('ix_ayah_page'), 'ayah', ['page'], unique=False)
    op.create_index(op.f('ix_ayah_revelation_order'), 'ayah', ['revelation_order'], unique=False)
    op.create_index(op.f('ix_ayah_revelation_place'), 'ayah', ['revelation_place'], unique=False)
    op.create_index(op.f('ix_ayah_ruku'), 'ayah', ['ruku'], unique=False)
    op.create_index('ix_ayah_search', 'ayah', ['text_search'], unique=False)
    op.create_index(op.f('ix_ayah_surah_id'), 'ayah', ['surah_id'], unique=False)
    op.create_table('concept_root',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.PrimaryKeyConstraint('concept_id', 'root_id')
    )
    op.create_table('hadith',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('book', sa.String(length=256), nullable=True),
    sa.Column('chapter', sa.String(length=512), nullable=True),
    sa.Column('text_ar', sa.Text(), nullable=True),
    sa.Column('text_search', sa.Text(), nullable=True),
    sa.Column('text_translation', sa.Text(), nullable=True),
    sa.Column('translation_language', sa.String(length=8), nullable=True),
    sa.Column('grading', sa.String(length=32), nullable=False),
    sa.Column('graded_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'number', name='uq_hadith_ref')
    )
    op.create_index(op.f('ix_hadith_collection'), 'hadith', ['collection'], unique=False)
    op.create_index(op.f('ix_hadith_edition_id'), 'hadith', ['edition_id'], unique=False)
    op.create_index(op.f('ix_hadith_grading'), 'hadith', ['grading'], unique=False)
    op.create_index(op.f('ix_hadith_number'), 'hadith', ['number'], unique=False)
    op.create_table('lemma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('lemma_display', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma', 'root_id', name='uq_lemma')
    )
    op.create_index(op.f('ix_lemma_lemma'), 'lemma', ['lemma'], unique=False)
    op.create_index(op.f('ix_lemma_root_id'), 'lemma', ['root_id'], unique=False)
    op.create_table('lexicon_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('headword', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexicon_entry_edition_id'), 'lexicon_entry', ['edition_id'], unique=False)
    op.create_index(op.f('ix_lexicon_entry_headword'), 'lexicon_entry', ['headword'], unique=False)
    op.create_index(op.f('ix_lexicon_entry_root_id'), 'lexicon_entry', ['root_id'], unique=False)
    op.create_table('api_key_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', 'provider', name='uq_api_key')
    )
    op.create_index(op.f('ix_api_key_record_org_id'), 'api_key_record', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_key_record_provider'), 'api_key_record', ['provider'], unique=False)
    op.create_index(op.f('ix_api_key_record_user_id'), 'api_key_record', ['user_id'], unique=False)
    op.create_table('ayah_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ayah_id', sa.Integer(), nullable=False),
    sa.Column('dst_ayah_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['dst_ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['src_ayah_id'], ['ayah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_ayah_id', 'dst_ayah_id', 'kind', name='uq_ayah_link')
    )
    op.create_index(op.f('ix_ayah_link_dst_ayah_id'), 'ayah_link', ['dst_ayah_id'], unique=False)
    op.create_index(op.f('ix_ayah_link_kind'), 'ayah_link', ['kind'], unique=False)
    op.create_index(op.f('ix_ayah_link_src_ayah_id'), 'ayah_link', ['src_ayah_id'], unique=False)
    op.create_table('concept_ayah',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('concept_id', 'ayah_id')
    )
    op.create_table('conditional_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('particle', sa.String(length=16), nullable=False),
    sa.Column('particle_form', sa.String(length=32), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('consequence_text', sa.Text(), nullable=False),
    sa.Column('apodosis_marker', sa.String(length=16), nullable=True),
    sa.Column('condition_roots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('consequence_roots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('word_start', sa.Integer(), nullable=False),
    sa.Column('word_end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditional_structure_ayah_id'), 'conditional_structure', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_conditional_structure_particle'), 'conditional_structure', ['particle'], unique=False)
    op.create_index(op.f('ix_conditional_structure_surah_id'), 'conditional_structure', ['surah_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('ayah_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('root_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_fingerprint'), 'finding', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_finding_org_id'), 'finding', ['org_id'], unique=False)
    op.create_index(op.f('ix_finding_review_status'), 'finding', ['review_status'], unique=False)
    op.create_index(op.f('ix_finding_run_id'), 'finding', ['run_id'], unique=False)
    op.create_table('hadith_ayah_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hadith_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['hadith_id'], ['hadith.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hadith_id', 'ayah_id', name='uq_hadith_ayah')
    )
    op.create_index(op.f('ix_hadith_ayah_link_ayah_id'), 'hadith_ayah_link', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_hadith_ayah_link_hadith_id'), 'hadith_ayah_link', ['hadith_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('compiled_query', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('abandoned_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('believed','testing','tested','supported','refuted','abandoned')", name='ck_hypothesis_status'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['hypothesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_org_id'), 'hypothesis', ['org_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_status'), 'hypothesis', ['status'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance in ('retrieved','system_suggested','own_note')", name='ck_note_provenance'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_author_id'), 'note', ['author_id'], unique=False)
    op.create_index(op.f('ix_note_org_id'), 'note', ['org_id'], unique=False)
    op.create_index(op.f('ix_note_provenance'), 'note', ['provenance'], unique=False)
    op.create_table('research_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ledger', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_ceiling_usd', sa.Float(), nullable=True),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_run_author_id'), 'research_run', ['author_id'], unique=False)
    op.create_index(op.f('ix_research_run_org_id'), 'research_run', ['org_id'], unique=False)
    op.create_index(op.f('ix_research_run_status'), 'research_run', ['status'], unique=False)
    op.create_table('search_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('ayah_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_id', name='uq_search_doc')
    )
    op.create_index(op.f('ix_search_doc_ayah_id'), 'search_doc', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_search_doc_edition_id'), 'search_doc', ['edition_id'], unique=False)
    op.create_index(op.f('ix_search_doc_kind'), 'search_doc', ['kind'], unique=False)
    op.create_index(op.f('ix_search_doc_language'), 'search_doc', ['language'], unique=False)
    op.create_index(op.f('ix_search_doc_ref_id'), 'search_doc', ['ref_id'], unique=False)
    op.create_table('tafsir_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_start', sa.Integer(), nullable=False),
    sa.Column('ayah_end', sa.Integer(), nullable=False),
    sa.Column('ayah_id_start', sa.Integer(), nullable=False),
    sa.Column('ayah_id_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ayah_id_start'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tafsir_entry_ayah_end'), 'tafsir_entry', ['ayah_end'], unique=False)
    op.create_index(op.f('ix_tafsir_entry_ayah_id_start'), 'tafsir_entry', ['ayah_id_start'], unique=False)
    op.create_index(op.f('ix_tafsir_entry_ayah_start'), 'tafsir_entry', ['ayah_start'], unique=False)
    op.create_index(op.f('ix_tafsir_entry_edition_id'), 'tafsir_entry', ['edition_id'], unique=False)
    op.create_index(op.f('ix_tafsir_entry_surah_id'), 'tafsir_entry', ['surah_id'], unique=False)
    op.create_index('ix_tafsir_range', 'tafsir_entry', ['edition_id', 'surah_id', 'ayah_start', 'ayah_end'], unique=False)
    op.create_table('topic_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_registration_org_id'), 'topic_registration', ['org_id'], unique=False)
    op.create_index(op.f('ix_topic_registration_slug'), 'topic_registration', ['slug'], unique=False)
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_num', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'ayah_id', name='uq_translation')
    )
    op.create_index(op.f('ix_translation_ayah_id'), 'translation', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_translation_edition_id'), 'translation', ['edition_id'], unique=False)
    op.create_index(op.f('ix_translation_surah_id'), 'translation', ['surah_id'], unique=False)
    op.create_table('usage_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_record_org_id'), 'usage_record', ['org_id'], unique=False)
    op.create_index(op.f('ix_usage_record_run_id'), 'usage_record', ['run_id'], unique=False)
    op.create_index(op.f('ix_usage_record_user_id'), 'usage_record', ['user_id'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_num', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('text_search', sa.String(length=128), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('lemma_id', sa.Integer(), nullable=True),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemma.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ayah_id', 'position', name='uq_word_pos')
    )
    op.create_index(op.f('ix_word_ayah_id'), 'word', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_word_lemma_id'), 'word', ['lemma_id'], unique=False)
    op.create_index(op.f('ix_word_pos'), 'word', ['pos'], unique=False)
    op.create_index(op.f('ix_word_root_id'), 'word', ['root_id'], unique=False)
    op.create_index(op.f('ix_word_surah_id'), 'word', ['surah_id'], unique=False)
    op.create_index(op.f('ix_word_text_search'), 'word', ['text_search'], unique=False)
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON().with_variant(postgresql.ARRAY(sa.Float()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['search_doc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'model', name='uq_embedding')
    )
    op.create_index(op.f('ix_embedding_doc_id'), 'embedding', ['doc_id'], unique=False)
    op.create_index(op.f('ix_embedding_model'), 'embedding', ['model'], unique=False)
    op.create_table('hypothesis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('compiled_query', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('supporting', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('violating', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('statistics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_run_hypothesis_id'), 'hypothesis_run', ['hypothesis_id'], unique=False)
    op.create_table('note_anchor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_anchor_ayah_id'), 'note_anchor', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_note_anchor_note_id'), 'note_anchor', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_anchor_root_id'), 'note_anchor', ['root_id'], unique=False)
    op.create_table('search_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('tf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['search_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posting_term_doc', 'search_posting', ['term', 'doc_id'], unique=False)
    op.create_index(op.f('ix_search_posting_doc_id'), 'search_posting', ['doc_id'], unique=False)
    op.create_index(op.f('ix_search_posting_term'), 'search_posting', ['term'], unique=False)
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=64), nullable=False),
    sa.Column('form_search', sa.String(length=64), nullable=False),
    sa.Column('pos_class', sa.String(length=8), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('lemma_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(length=8), nullable=True),
    sa.Column('verb_form', sa.String(length=8), nullable=True),
    sa.Column('mood', sa.String(length=8), nullable=True),
    sa.Column('voice', sa.String(length=8), nullable=True),
    sa.Column('case', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('person', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('number', sa.String(length=4), nullable=True),
    sa.Column('derivation', sa.String(length=16), nullable=True),
    sa.Column('is_prefix', sa.Boolean(), nullable=False),
    sa.Column('is_suffix', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemma.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['root.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'position', name='uq_segment_pos')
    )
    op.create_index(op.f('ix_segment_aspect'), 'segment', ['aspect'], unique=False)
    op.create_index(op.f('ix_segment_ayah_id'), 'segment', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_segment_derivation'), 'segment', ['derivation'], unique=False)
    op.create_index(op.f('ix_segment_form_search'), 'segment', ['form_search'], unique=False)
    op.create_index(op.f('ix_segment_lemma_id'), 'segment', ['lemma_id'], unique=False)
    op.create_index(op.f('ix_segment_root_id'), 'segment', ['root_id'], unique=False)
    op.create_index(op.f('ix_segment_surah_id'), 'segment', ['surah_id'], unique=False)
    op.create_index(op.f('ix_segment_tag'), 'segment', ['tag'], unique=False)
    op.create_index(op.f('ix_segment_verb_form'), 'segment', ['verb_form'], unique=False)
    op.create_index(op.f('ix_segment_word_id'), 'segment', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_word_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_verb_form'), table_name='segment')
    op.drop_index(op.f('ix_segment_tag'), table_name='segment')
    op.drop_index(op.f('ix_segment_surah_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_root_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_lemma_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_form_search'), table_name='segment')
    op.drop_index(op.f('ix_segment_derivation'), table_name='segment')
    op.drop_index(op.f('ix_segment_ayah_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_aspect'), table_name='segment')
    op.drop_table('segment')
    op.drop_index(op.f('ix_search_posting_term'), table_name='search_posting')
    op.drop_index(op.f('ix_search_posting_doc_id'), table_name='search_posting')
    op.drop_index('ix_posting_term_doc', table_name='search_posting')
    op.drop_table('search_posting')
    op.drop_index(op.f('ix_note_anchor_root_id'), table_name='note_anchor')
    op.drop_index(op.f('ix_note_anchor_note_id'), table_name='note_anchor')
    op.drop_index(op.f('ix_note_anchor_ayah_id'), table_name='note_anchor')
    op.drop_table('note_anchor')
    op.drop_index(op.f('ix_hypothesis_run_hypothesis_id'), table_name='hypothesis_run')
    op.drop_table('hypothesis_run')
    op.drop_index(op.f('ix_embedding_model'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_doc_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_index(op.f('ix_word_text_search'), table_name='word')
    op.drop_index(op.f('ix_word_surah_id'), table_name='word')
    op.drop_index(op.f('ix_word_root_id'), table_name='word')
    op.drop_index(op.f('ix_word_pos'), table_name='word')
    op.drop_index(op.f('ix_word_lemma_id'), table_name='word')
    op.drop_index(op.f('ix_word_ayah_id'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_usage_record_user_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_run_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_org_id'), table_name='usage_record')
    op.drop_table('usage_record')
    op.drop_index(op.f('ix_translation_surah_id'), table_name='translation')
    op.drop_index(op.f('ix_translation_edition_id'), table_name='translation')
    op.drop_index(op.f('ix_translation_ayah_id'), table_name='translation')
    op.drop_table('translation')
    op.drop_index(op.f('ix_topic_registration_slug'), table_name='topic_registration')
    op.drop_index(op.f('ix_topic_registration_org_id'), table_name='topic_registration')
    op.drop_table('topic_registration')
    op.drop_index('ix_tafsir_range', table_name='tafsir_entry')
    op.drop_index(op.f('ix_tafsir_entry_surah_id'), table_name='tafsir_entry')
    op.drop_index(op.f('ix_tafsir_entry_edition_id'), table_name='tafsir_entry')
    op.drop_index(op.f('ix_tafsir_entry_ayah_start'), table_name='tafsir_entry')
    op.drop_index(op.f('ix_tafsir_entry_ayah_id_start'), table_name='tafsir_entry')
    op.drop_index(op.f('ix_tafsir_entry_ayah_end'), table_name='tafsir_entry')
    op.drop_table('tafsir_entry')
    op.drop_index(op.f('ix_search_doc_ref_id'), table_name='search_doc')
    op.drop_index(op.f('ix_search_doc_language'), table_name='search_doc')
    op.drop_index(op.f('ix_search_doc_kind'), table_name='search_doc')
    op.drop_index(op.f('ix_search_doc_edition_id'), table_name='search_doc')
    op.drop_index(op.f('ix_search_doc_ayah_id'), table_name='search_doc')
    op.drop_table('search_doc')
    op.drop_index(op.f('ix_research_run_status'), table_name='research_run')
    op.drop_index(op.f('ix_research_run_org_id'), table_name='research_run')
    op.drop_index(op.f('ix_research_run_author_id'), table_name='research_run')
    op.drop_table('research_run')
    op.drop_index(op.f('ix_note_provenance'), table_name='note')
    op.drop_index(op.f('ix_note_org_id'), table_name='note')
    op.drop_index(op.f('ix_note_author_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_hypothesis_status'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_org_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_hadith_ayah_link_hadith_id'), table_name='hadith_ayah_link')
    op.drop_index(op.f('ix_hadith_ayah_link_ayah_id'), table_name='hadith_ayah_link')
    op.drop_table('hadith_ayah_link')
    op.drop_index(op.f('ix_finding_run_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_review_status'), table_name='finding')
    op.drop_index(op.f('ix_finding_org_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_fingerprint'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_conditional_structure_surah_id'), table_name='conditional_structure')
    op.drop_index(op.f('ix_conditional_structure_particle'), table_name='conditional_structure')
    op.drop_index(op.f('ix_conditional_structure_ayah_id'), table_name='conditional_structure')
    op.drop_table('conditional_structure')
    op.drop_table('concept_ayah')
    op.drop_index(op.f('ix_ayah_link_src_ayah_id'), table_name='ayah_link')
    op.drop_index(op.f('ix_ayah_link_kind'), table_name='ayah_link')
    op.drop_index(op.f('ix_ayah_link_dst_ayah_id'), table_name='ayah_link')
    op.drop_table('ayah_link')
    op.drop_index(op.f('ix_api_key_record_user_id'), table_name='api_key_record')
    op.drop_index(op.f('ix_api_key_record_provider'), table_name='api_key_record')
    op.drop_index(op.f('ix_api_key_record_org_id'), table_name='api_key_record')
    op.drop_table('api_key_record')
    op.drop_index(op.f('ix_lexicon_entry_root_id'), table_name='lexicon_entry')
    op.drop_index(op.f('ix_lexicon_entry_headword'), table_name='lexicon_entry')
    op.drop_index(op.f('ix_lexicon_entry_edition_id'), table_name='lexicon_entry')
    op.drop_table('lexicon_entry')
    op.drop_index(op.f('ix_lemma_root_id'), table_name='lemma')
    op.drop_index(op.f('ix_lemma_lemma'), table_name='lemma')
    op.drop_table('lemma')
    op.drop_index(op.f('ix_hadith_number'), table_name='hadith')
    op.drop_index(op.f('ix_hadith_grading'), table_name='hadith')
    op.drop_index(op.f('ix_hadith_edition_id'), table_name='hadith')
    op.drop_index(op.f('ix_hadith_collection'), table_name='hadith')
    op.drop_table('hadith')
    op.drop_table('concept_root')
    op.drop_index(op.f('ix_ayah_surah_id'), table_name='ayah')
    op.drop_index('ix_ayah_search', table_name='ayah')
    op.drop_index(op.f('ix_ayah_ruku'), table_name='ayah')
    op.drop_index(op.f('ix_ayah_revelation_place'), table_name='ayah')
    op.drop_index(op.f('ix_ayah_revelation_order'), table_name='ayah')
    op.drop_index(op.f('ix_ayah_page'), table_name='ayah')
    op.drop_index('ix_ayah_loose', table_name='ayah')
    op.drop_index(op.f('ix_ayah_juz'), table_name='ayah')
    op.drop_table('ayah')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_oidc_subject'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_surah_revelation_order'), table_name='surah')
    op.drop_table('surah')
    op.drop_table('search_term')
    op.drop_index(op.f('ix_root_root'), table_name='root')
    op.drop_table('root')
    op.drop_index(op.f('ix_passage_surah_id'), table_name='passage')
    op.drop_table('passage')
    op.drop_index(op.f('ix_organisation_slug'), table_name='organisation')
    op.drop_table('organisation')
    op.drop_index(op.f('ix_ingest_log_step'), table_name='ingest_log')
    op.drop_table('ingest_log')
    op.drop_index(op.f('ix_edition_slug'), table_name='edition')
    op.drop_index(op.f('ix_edition_license_status'), table_name='edition')
    op.drop_index(op.f('ix_edition_language'), table_name='edition')
    op.drop_index(op.f('ix_edition_kind'), table_name='edition')
    op.drop_table('edition')
    op.drop_index(op.f('ix_concept_slug'), table_name='concept')
    op.drop_table('concept')
    op.drop_index(op.f('ix_cache_entry_kind'), table_name='cache_entry')
    op.drop_table('cache_entry')
    # ### end Alembic commands ###
