"""narrator normalised chain position

Revision ID: 3f8af635843e
Revises: ed70cbdba3a0
Create Date: 2026-09-19 08:22:52.095703
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3f8af635843e'
down_revision = 'ed70cbdba3a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narrator', sa.Column('min_position', sa.Float(), nullable=False, server_default='0'))
    op.add_column('narrator', sa.Column('max_position', sa.Float(), nullable=False, server_default='0'))
    op.add_column('narrator', sa.Column('mean_position', sa.Float(), nullable=False, server_default='0'))
    op.add_column('narrator', sa.Column('position_spread', sa.Float(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_narrator_position_spread'), 'narrator', ['position_spread'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narrator_position_spread'), table_name='narrator')
    op.drop_column('narrator', 'position_spread')
    op.drop_column('narrator', 'mean_position')
    op.drop_column('narrator', 'max_position')
    op.drop_column('narrator', 'min_position')
    # ### end Alembic commands ###
