"""claim registry with an append-only history

Revision ID: 4afce00a8927
Revises: 3f8af635843e
Create Date: 2026-09-19 16:19:11.281272
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4afce00a8927'
down_revision = '3f8af635843e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_level', sa.String(length=4), nullable=False),
    sa.Column('ayah_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('root_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('objections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_level in ('L0','L1','L2','L3','L4')", name='ck_claim_level'),
    sa.CheckConstraint("status in ('proposed','under_review','supported','qualified','contested','refuted','withdrawn')", name='ck_claim_status'),
    sa.CheckConstraint('length(statement) > 0', name='ck_claim_statement_present'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_author_id'), 'claim', ['author_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_level'), 'claim', ['evidence_level'], unique=False)
    op.create_index(op.f('ix_claim_finding_id'), 'claim', ['finding_id'], unique=False)
    op.create_index(op.f('ix_claim_hypothesis_id'), 'claim', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_claim_org_id'), 'claim', ['org_id'], unique=False)
    op.create_index(op.f('ix_claim_slug'), 'claim', ['slug'], unique=True)
    op.create_index(op.f('ix_claim_status'), 'claim', ['status'], unique=False)
    op.create_index(op.f('ix_claim_superseded_by_id'), 'claim', ['superseded_by_id'], unique=False)
    op.create_table('claim_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(reason) > 0', name='ck_claim_event_reason_present'),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_event_actor_id'), 'claim_event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_claim_event_claim_id'), 'claim_event', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_event_kind'), 'claim_event', ['kind'], unique=False)
    op.create_index('ix_claim_event_time', 'claim_event', ['claim_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claim_event_time', table_name='claim_event')
    op.drop_index(op.f('ix_claim_event_kind'), table_name='claim_event')
    op.drop_index(op.f('ix_claim_event_claim_id'), table_name='claim_event')
    op.drop_index(op.f('ix_claim_event_actor_id'), table_name='claim_event')
    op.drop_table('claim_event')
    op.drop_index(op.f('ix_claim_superseded_by_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_status'), table_name='claim')
    op.drop_index(op.f('ix_claim_slug'), table_name='claim')
    op.drop_index(op.f('ix_claim_org_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_hypothesis_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_finding_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_evidence_level'), table_name='claim')
    op.drop_index(op.f('ix_claim_author_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
