"""ahkam positions and ijaz claims

Revision ID: 7b21d42966e8
Revises: d51046825a65
Create Date: 2026-09-02 06:04:50.255429
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7b21d42966e8'
down_revision = 'd51046825a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ijaz_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=False),
    sa.Column('key_term', sa.String(length=64), nullable=False),
    sa.Column('root', sa.String(length=32), nullable=True),
    sa.Column('proponent', sa.String(length=256), nullable=True),
    sa.Column('proponent_year', sa.Integer(), nullable=True),
    sa.Column('requires_meaning', sa.Text(), nullable=False),
    sa.Column('science_status', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('unsourced', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level in ('L3','L4')", name='ck_ijaz_level_never_asserted'),
    sa.CheckConstraint('length(claim) > 0', name='ck_ijaz_claim_present'),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ijaz_claim_ayah_id'), 'ijaz_claim', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_ijaz_claim_slug'), 'ijaz_claim', ['slug'], unique=True)
    op.create_table('madhhab_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('madhhab', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('source_work', sa.String(length=256), nullable=False),
    sa.Column('scholar', sa.String(length=256), nullable=True),
    sa.Column('ayah_id', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(madhhab) > 0', name='ck_madhhab_school_present'),
    sa.CheckConstraint('length(position) > 0', name='ck_madhhab_position_present'),
    sa.CheckConstraint('length(source_work) > 0', name='ck_madhhab_source_present'),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_madhhab_position_ayah_id'), 'madhhab_position', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_madhhab_position_madhhab'), 'madhhab_position', ['madhhab'], unique=False)
    op.create_index(op.f('ix_madhhab_position_topic'), 'madhhab_position', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_madhhab_position_topic'), table_name='madhhab_position')
    op.drop_index(op.f('ix_madhhab_position_madhhab'), table_name='madhhab_position')
    op.drop_index(op.f('ix_madhhab_position_ayah_id'), table_name='madhhab_position')
    op.drop_table('madhhab_position')
    op.drop_index(op.f('ix_ijaz_claim_slug'), table_name='ijaz_claim')
    op.drop_index(op.f('ix_ijaz_claim_ayah_id'), table_name='ijaz_claim')
    op.drop_table('ijaz_claim')
    # ### end Alembic commands ###
