"""community: posts, comments, votes, flags

Revision ID: 8ae3d8eaf023
Revises: 1f6436e40851
Create Date: 2026-09-01 20:06:16.456496
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8ae3d8eaf023'
down_revision = '1f6436e40851'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resolution in ('open','upheld','dismissed')", name='ck_flag_resolution'),
    sa.CheckConstraint("target_kind in ('post','comment')", name='ck_flag_target'),
    sa.ForeignKeyConstraint(['reporter_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_kind', 'target_id', 'reporter_id', name='uq_flag_once_per_reporter')
    )
    op.create_index(op.f('ix_post_flag_resolution'), 'post_flag', ['resolution'], unique=False)
    op.create_index(op.f('ix_post_flag_target_id'), 'post_flag', ['target_id'], unique=False)
    op.create_index(op.f('ix_post_flag_target_kind'), 'post_flag', ['target_kind'], unique=False)
    op.create_table('post_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_kind in ('post','comment')", name='ck_vote_target'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_kind', 'target_id', 'user_id', name='uq_vote_once')
    )
    op.create_index(op.f('ix_post_vote_target_id'), 'post_vote', ['target_id'], unique=False)
    op.create_index(op.f('ix_post_vote_target_kind'), 'post_vote', ['target_kind'], unique=False)
    op.create_index(op.f('ix_post_vote_user_id'), 'post_vote', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_rendered', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('ayah_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('roots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind in ('question','insight','finding','hypothesis','correction')", name='ck_post_kind'),
    sa.CheckConstraint("status in ('visible','hidden','removed')", name='ck_post_status'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index('ix_post_feed', 'post', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_finding_id'), 'post', ['finding_id'], unique=False)
    op.create_index(op.f('ix_post_flag_count'), 'post', ['flag_count'], unique=False)
    op.create_index(op.f('ix_post_hypothesis_id'), 'post', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_post_kind'), 'post', ['kind'], unique=False)
    op.create_index(op.f('ix_post_note_id'), 'post', ['note_id'], unique=False)
    op.create_index(op.f('ix_post_org_id'), 'post', ['org_id'], unique=False)
    op.create_index(op.f('ix_post_run_id'), 'post', ['run_id'], unique=False)
    op.create_index(op.f('ix_post_status'), 'post', ['status'], unique=False)
    op.create_index(op.f('ix_post_upvotes'), 'post', ['upvotes'], unique=False)
    op.create_index('ix_post_useful', 'post', ['status', 'upvotes'], unique=False)
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_rendered', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('visible','hidden','removed')", name='ck_comment_status'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_author_id'), 'post_comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_comment_flag_count'), 'post_comment', ['flag_count'], unique=False)
    op.create_index(op.f('ix_post_comment_parent_id'), 'post_comment', ['parent_id'], unique=False)
    op.create_index(op.f('ix_post_comment_post_id'), 'post_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comment_status'), 'post_comment', ['status'], unique=False)
    op.create_index(op.f('ix_app_user_oidc_subject'), 'app_user', ['oidc_subject'], unique=False)
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_check_constraint('ck_user_role', 'app_user', "role in ('reader','researcher','reviewer','admin')")
    op.create_index('ix_ayah_loose', 'ayah', ['text_loose'], unique=False)
    op.create_index(op.f('ix_finding_org_id'), 'finding', ['org_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_org_id'), 'hypothesis', ['org_id'], unique=False)
    op.create_index(op.f('ix_note_org_id'), 'note', ['org_id'], unique=False)
    op.create_index(op.f('ix_research_run_author_id'), 'research_run', ['author_id'], unique=False)
    op.create_index(op.f('ix_research_run_org_id'), 'research_run', ['org_id'], unique=False)
    op.create_index(op.f('ix_topic_registration_org_id'), 'topic_registration', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_registration_org_id'), table_name='topic_registration')
    op.drop_index(op.f('ix_research_run_org_id'), table_name='research_run')
    op.drop_index(op.f('ix_research_run_author_id'), table_name='research_run')
    op.drop_index(op.f('ix_note_org_id'), table_name='note')
    op.drop_index(op.f('ix_hypothesis_org_id'), table_name='hypothesis')
    op.drop_index(op.f('ix_finding_org_id'), table_name='finding')
    op.drop_index('ix_ayah_loose', table_name='ayah')
    op.drop_constraint('ck_user_role', 'app_user', type_='check')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_oidc_subject'), table_name='app_user')
    op.drop_index(op.f('ix_post_comment_status'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_post_id'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_parent_id'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_flag_count'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_author_id'), table_name='post_comment')
    op.drop_table('post_comment')
    op.drop_index('ix_post_useful', table_name='post')
    op.drop_index(op.f('ix_post_upvotes'), table_name='post')
    op.drop_index(op.f('ix_post_status'), table_name='post')
    op.drop_index(op.f('ix_post_run_id'), table_name='post')
    op.drop_index(op.f('ix_post_org_id'), table_name='post')
    op.drop_index(op.f('ix_post_note_id'), table_name='post')
    op.drop_index(op.f('ix_post_kind'), table_name='post')
    op.drop_index(op.f('ix_post_hypothesis_id'), table_name='post')
    op.drop_index(op.f('ix_post_flag_count'), table_name='post')
    op.drop_index(op.f('ix_post_finding_id'), table_name='post')
    op.drop_index('ix_post_feed', table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_post_vote_user_id'), table_name='post_vote')
    op.drop_index(op.f('ix_post_vote_target_kind'), table_name='post_vote')
    op.drop_index(op.f('ix_post_vote_target_id'), table_name='post_vote')
    op.drop_table('post_vote')
    op.drop_index(op.f('ix_post_flag_target_kind'), table_name='post_flag')
    op.drop_index(op.f('ix_post_flag_target_id'), table_name='post_flag')
    op.drop_index(op.f('ix_post_flag_resolution'), table_name='post_flag')
    op.drop_table('post_flag')
    # ### end Alembic commands ###
