"""study groups: channels, messages, reactions

Revision ID: 9cd88ae8c80b
Revises: 7b21d42966e8
Create Date: 2026-09-02 06:34:25.054474
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9cd88ae8c80b'
down_revision = '7b21d42966e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='ck_group_name_present'),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_group_owner_id'), 'study_group', ['owner_id'], unique=False)
    op.create_index(op.f('ix_study_group_slug'), 'study_group', ['slug'], unique=True)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('topic_rendered', sa.Text(), nullable=False),
    sa.Column('topic_citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='ck_channel_name_present'),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug', name='uq_channel_slug')
    )
    op.create_index(op.f('ix_channel_group_id'), 'channel', ['group_id'], unique=False)
    op.create_index(op.f('ix_channel_slug'), 'channel', ['slug'], unique=False)
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('owner','moderator','member','reader')", name='ck_group_role'),
    sa.CheckConstraint('user_id is not null or invited_email is not null', name='ck_group_member_identified'),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'invited_email', name='uq_group_invite'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user')
    )
    op.create_index(op.f('ix_group_member_group_id'), 'group_member', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_member_invited_email'), 'group_member', ['invited_email'], unique=False)
    op.create_index(op.f('ix_group_member_user_id'), 'group_member', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_rendered', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ayah_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author_id'), 'message', ['author_id'], unique=False)
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index('ix_message_channel_time', 'message', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_group_id'), 'message', ['group_id'], unique=False)
    op.create_index(op.f('ix_message_parent_id'), 'message', ['parent_id'], unique=False)
    op.create_index('ix_message_thread', 'message', ['parent_id', 'created_at'], unique=False)
    op.create_table('message_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reaction_once')
    )
    op.create_index(op.f('ix_message_reaction_message_id'), 'message_reaction', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reaction_user_id'), 'message_reaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reaction_user_id'), table_name='message_reaction')
    op.drop_index(op.f('ix_message_reaction_message_id'), table_name='message_reaction')
    op.drop_table('message_reaction')
    op.drop_index('ix_message_thread', table_name='message')
    op.drop_index(op.f('ix_message_parent_id'), table_name='message')
    op.drop_index(op.f('ix_message_group_id'), table_name='message')
    op.drop_index('ix_message_channel_time', table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_index(op.f('ix_message_author_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_group_member_user_id'), table_name='group_member')
    op.drop_index(op.f('ix_group_member_invited_email'), table_name='group_member')
    op.drop_index(op.f('ix_group_member_group_id'), table_name='group_member')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_channel_slug'), table_name='channel')
    op.drop_index(op.f('ix_channel_group_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_study_group_slug'), table_name='study_group')
    op.drop_index(op.f('ix_study_group_owner_id'), table_name='study_group')
    op.drop_table('study_group')
    # ### end Alembic commands ###
