"""asbab reports as first-class graded claims

Revision ID: a1a53f9017d6
Revises: 8ae3d8eaf023
Create Date: 2026-09-01 20:48:27.260681
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a1a53f9017d6'
down_revision = '8ae3d8eaf023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asbab_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('ayah_id', sa.Integer(), nullable=True),
    sa.Column('surah_id', sa.Integer(), nullable=True),
    sa.Column('ayah_num', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('claimant', sa.String(length=256), nullable=False),
    sa.Column('source_work', sa.String(length=256), nullable=False),
    sa.Column('reference', sa.String(length=256), nullable=True),
    sa.Column('grade', sa.String(length=24), nullable=False),
    sa.Column('graded_by', sa.String(length=256), nullable=True),
    sa.Column('mapping', sa.String(length=32), nullable=False),
    sa.Column('mapping_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('withheld_reason', sa.Text(), nullable=True),
    sa.Column('source_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("grade in ('sahih','hasan','daif','mursal','ungraded')", name='ck_asbab_grade'),
    sa.CheckConstraint("status in ('published','withheld')", name='ck_asbab_status'),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asbab_lookup', 'asbab_report', ['ayah_id', 'status'], unique=False)
    op.create_index(op.f('ix_asbab_report_ayah_id'), 'asbab_report', ['ayah_id'], unique=False)
    op.create_index(op.f('ix_asbab_report_edition_id'), 'asbab_report', ['edition_id'], unique=False)
    op.create_index(op.f('ix_asbab_report_grade'), 'asbab_report', ['grade'], unique=False)
    op.create_index(op.f('ix_asbab_report_mapping'), 'asbab_report', ['mapping'], unique=False)
    op.create_index(op.f('ix_asbab_report_status'), 'asbab_report', ['status'], unique=False)
    op.create_index(op.f('ix_asbab_report_surah_id'), 'asbab_report', ['surah_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asbab_report_surah_id'), table_name='asbab_report')
    op.drop_index(op.f('ix_asbab_report_status'), table_name='asbab_report')
    op.drop_index(op.f('ix_asbab_report_mapping'), table_name='asbab_report')
    op.drop_index(op.f('ix_asbab_report_grade'), table_name='asbab_report')
    op.drop_index(op.f('ix_asbab_report_edition_id'), table_name='asbab_report')
    op.drop_index(op.f('ix_asbab_report_ayah_id'), table_name='asbab_report')
    op.drop_index('ix_asbab_lookup', table_name='asbab_report')
    op.drop_table('asbab_report')
    # ### end Alembic commands ###
