"""agent memory

Revision ID: a31fb4cb8e6c
Revises: c3e9754122e8
Create Date: 2026-09-19 18:06:34.665237
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a31fb4cb8e6c'
down_revision = 'c3e9754122e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_level', sa.String(length=4), nullable=False),
    sa.Column('corpus_revision', sa.String(length=32), nullable=False),
    sa.Column('confirmations', sa.Integer(), server_default='1', nullable=False),
    sa.Column('digest', sa.String(length=32), nullable=False),
    sa.Column('stale_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('result','dead_end','caveat')", name='ck_memory_kind'),
    sa.CheckConstraint('confirmations >= 1', name='ck_memory_confirmations'),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'digest', name='uq_memory_digest')
    )
    op.create_index(op.f('ix_memory_entry_corpus_revision'), 'memory_entry', ['corpus_revision'], unique=False)
    op.create_index(op.f('ix_memory_entry_digest'), 'memory_entry', ['digest'], unique=False)
    op.create_index(op.f('ix_memory_entry_finding_id'), 'memory_entry', ['finding_id'], unique=False)
    op.create_index(op.f('ix_memory_entry_key'), 'memory_entry', ['key'], unique=False)
    op.create_index(op.f('ix_memory_entry_kind'), 'memory_entry', ['kind'], unique=False)
    op.create_index(op.f('ix_memory_entry_org_id'), 'memory_entry', ['org_id'], unique=False)
    op.create_index(op.f('ix_memory_entry_run_id'), 'memory_entry', ['run_id'], unique=False)
    op.create_index('ix_memory_recall', 'memory_entry', ['org_id', 'key', 'stale_reason'], unique=False)
    # ### end Alembic commands ###

    # uq_memory_digest does not bind the personal (org-less) case: Postgres
    # treats NULLs as distinct, so a UNIQUE(org_id, digest) allows any number of
    # rows with org_id IS NULL and the same digest. remember() looks before it
    # inserts, but two concurrent runs learning the same thing would both look,
    # both miss, and both insert — splitting one memory's confirmation count
    # across two rows. A partial index closes it in the database, where the race
    # actually is.
    op.create_index(
        'uq_memory_digest_personal',
        'memory_entry',
        ['digest'],
        unique=True,
        postgresql_where=sa.text('org_id IS NULL'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memory_digest_personal', table_name='memory_entry')
    op.drop_index('ix_memory_recall', table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_run_id'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_org_id'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_kind'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_key'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_finding_id'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_digest'), table_name='memory_entry')
    op.drop_index(op.f('ix_memory_entry_corpus_revision'), table_name='memory_entry')
    op.drop_table('memory_entry')
    # ### end Alembic commands ###
