"""study series and the trainer

Revision ID: c3e9754122e8
Revises: 4afce00a8927
Create Date: 2026-09-19 17:54:02.013300
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c3e9754122e8'
down_revision = '4afce00a8927'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(title) > 0', name='ck_series_title_present'),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_series_author_id'), 'study_series', ['author_id'], unique=False)
    op.create_index(op.f('ix_study_series_kind'), 'study_series', ['kind'], unique=False)
    op.create_index(op.f('ix_study_series_org_id'), 'study_series', ['org_id'], unique=False)
    op.create_index(op.f('ix_study_series_published'), 'study_series', ['published'], unique=False)
    op.create_index(op.f('ix_study_series_slug'), 'study_series', ['slug'], unique=True)
    op.create_table('trainer_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'subject', name='uq_trainer_card')
    )
    op.create_index(op.f('ix_trainer_card_kind'), 'trainer_card', ['kind'], unique=False)
    op.create_index(op.f('ix_trainer_card_user_id'), 'trainer_card', ['user_id'], unique=False)
    op.create_index('ix_trainer_due', 'trainer_card', ['user_id', 'due_at'], unique=False)
    op.create_table('series_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['study_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'position', name='uq_series_position')
    )
    op.create_index(op.f('ix_series_item_series_id'), 'series_item', ['series_id'], unique=False)
    op.create_table('series_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['study_series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'user_id', 'position', name='uq_series_progress')
    )
    op.create_index(op.f('ix_series_progress_series_id'), 'series_progress', ['series_id'], unique=False)
    op.create_index(op.f('ix_series_progress_user_id'), 'series_progress', ['user_id'], unique=False)
    op.create_table('trainer_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('interval_before', sa.Integer(), nullable=False),
    sa.Column('interval_after', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade between 0 and 5', name='ck_review_grade'),
    sa.ForeignKeyConstraint(['card_id'], ['trainer_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_review_card_id'), 'trainer_review', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_review_card_id'), table_name='trainer_review')
    op.drop_table('trainer_review')
    op.drop_index(op.f('ix_series_progress_user_id'), table_name='series_progress')
    op.drop_index(op.f('ix_series_progress_series_id'), table_name='series_progress')
    op.drop_table('series_progress')
    op.drop_index(op.f('ix_series_item_series_id'), table_name='series_item')
    op.drop_table('series_item')
    op.drop_index('ix_trainer_due', table_name='trainer_card')
    op.drop_index(op.f('ix_trainer_card_user_id'), table_name='trainer_card')
    op.drop_index(op.f('ix_trainer_card_kind'), table_name='trainer_card')
    op.drop_table('trainer_card')
    op.drop_index(op.f('ix_study_series_slug'), table_name='study_series')
    op.drop_index(op.f('ix_study_series_published'), table_name='study_series')
    op.drop_index(op.f('ix_study_series_org_id'), table_name='study_series')
    op.drop_index(op.f('ix_study_series_kind'), table_name='study_series')
    op.drop_index(op.f('ix_study_series_author_id'), table_name='study_series')
    op.drop_table('study_series')
    # ### end Alembic commands ###
