"""track D: sandbox sessions, naskh claims

Revision ID: d51046825a65
Revises: d514b5e0092a
Create Date: 2026-09-02 05:38:55.635605
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd51046825a65'
down_revision = 'd514b5e0092a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naskh_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abrogated_ayah_id', sa.Integer(), nullable=False),
    sa.Column('abrogating_ayah_id', sa.Integer(), nullable=True),
    sa.Column('claimant', sa.String(length=256), nullable=False),
    sa.Column('source_work', sa.String(length=256), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('rejected_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('ruling','recitation','both')", name='ck_naskh_kind'),
    sa.CheckConstraint('length(claimant) > 0', name='ck_naskh_claimant_present'),
    sa.CheckConstraint('length(source_work) > 0', name='ck_naskh_source_present'),
    sa.ForeignKeyConstraint(['abrogated_ayah_id'], ['ayah.id'], ),
    sa.ForeignKeyConstraint(['abrogating_ayah_id'], ['ayah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naskh_claim_abrogated_ayah_id'), 'naskh_claim', ['abrogated_ayah_id'], unique=False)
    op.create_index(op.f('ix_naskh_claim_abrogating_ayah_id'), 'naskh_claim', ['abrogating_ayah_id'], unique=False)
    op.create_table('sandbox_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('tests_run', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_session_owner_id'), 'sandbox_session', ['owner_id'], unique=False)
    op.create_table('sandbox_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('null_model', sa.Text(), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed', sa.Integer(), nullable=True),
    sa.Column('expected', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('corrected_p', sa.Float(), nullable=True),
    sa.Column('within_chance', sa.Boolean(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sandbox_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_test_session_id'), 'sandbox_test', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_test_session_id'), table_name='sandbox_test')
    op.drop_table('sandbox_test')
    op.drop_index(op.f('ix_sandbox_session_owner_id'), table_name='sandbox_session')
    op.drop_table('sandbox_session')
    op.drop_index(op.f('ix_naskh_claim_abrogating_ayah_id'), table_name='naskh_claim')
    op.drop_index(op.f('ix_naskh_claim_abrogated_ayah_id'), table_name='naskh_claim')
    op.drop_table('naskh_claim')
    # ### end Alembic commands ###
