"""segment ayah_index for sequence queries

Revision ID: d514b5e0092a
Revises: a1a53f9017d6
Create Date: 2026-09-01 20:55:58.012750
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd514b5e0092a'
down_revision = 'a1a53f9017d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('ayah_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_segment_ayah_index'), 'segment', ['ayah_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_ayah_index'), table_name='segment')
    op.drop_column('segment', 'ayah_index')
    # ### end Alembic commands ###
