"""rijal: narrators, gradings, chain positions, transmission edges

Revision ID: ed70cbdba3a0
Revises: 9cd88ae8c80b
Create Date: 2026-09-19 08:18:14.504229
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ed70cbdba3a0'
down_revision = '9cd88ae8c80b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('narration_count', sa.Integer(), nullable=False),
    sa.Column('min_depth', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('mean_depth', sa.Float(), nullable=False),
    sa.Column('depth_spread', sa.Integer(), nullable=False),
    sa.Column('death_year_hijri', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrator_canonical'), 'narrator', ['canonical'], unique=True)
    op.create_index(op.f('ix_narrator_depth_spread'), 'narrator', ['depth_spread'], unique=False)
    op.create_index(op.f('ix_narrator_narration_count'), 'narrator', ['narration_count'], unique=False)
    op.create_table('narrator_grading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrator_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('critic', sa.String(length=256), nullable=False),
    sa.Column('source_work', sa.String(length=256), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(critic) > 0', name='ck_grading_critic_present'),
    sa.CheckConstraint('length(source_work) > 0', name='ck_grading_source_present'),
    sa.ForeignKeyConstraint(['narrator_id'], ['narrator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrator_grading_grade'), 'narrator_grading', ['grade'], unique=False)
    op.create_index(op.f('ix_narrator_grading_narrator_id'), 'narrator_grading', ['narrator_id'], unique=False)
    op.create_table('transmission_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('collections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['narrator.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['narrator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'student_id', name='uq_transmission_edge')
    )
    op.create_index(op.f('ix_transmission_edge_student_id'), 'transmission_edge', ['student_id'], unique=False)
    op.create_index(op.f('ix_transmission_edge_teacher_id'), 'transmission_edge', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_transmission_edge_weight'), 'transmission_edge', ['weight'], unique=False)
    op.create_table('chain_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hadith_id', sa.Integer(), nullable=False),
    sa.Column('narrator_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hadith_id'], ['hadith.id'], ),
    sa.ForeignKeyConstraint(['narrator_id'], ['narrator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hadith_id', 'depth', name='uq_chain_slot')
    )
    op.create_index('ix_chain_narrator_depth', 'chain_position', ['narrator_id', 'depth'], unique=False)
    op.create_index(op.f('ix_chain_position_collection'), 'chain_position', ['collection'], unique=False)
    op.create_index(op.f('ix_chain_position_depth'), 'chain_position', ['depth'], unique=False)
    op.create_index(op.f('ix_chain_position_hadith_id'), 'chain_position', ['hadith_id'], unique=False)
    op.create_index(op.f('ix_chain_position_narrator_id'), 'chain_position', ['narrator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_position_narrator_id'), table_name='chain_position')
    op.drop_index(op.f('ix_chain_position_hadith_id'), table_name='chain_position')
    op.drop_index(op.f('ix_chain_position_depth'), table_name='chain_position')
    op.drop_index(op.f('ix_chain_position_collection'), table_name='chain_position')
    op.drop_index('ix_chain_narrator_depth', table_name='chain_position')
    op.drop_table('chain_position')
    op.drop_index(op.f('ix_transmission_edge_weight'), table_name='transmission_edge')
    op.drop_index(op.f('ix_transmission_edge_teacher_id'), table_name='transmission_edge')
    op.drop_index(op.f('ix_transmission_edge_student_id'), table_name='transmission_edge')
    op.drop_table('transmission_edge')
    op.drop_index(op.f('ix_narrator_grading_narrator_id'), table_name='narrator_grading')
    op.drop_index(op.f('ix_narrator_grading_grade'), table_name='narrator_grading')
    op.drop_table('narrator_grading')
    op.drop_index(op.f('ix_narrator_narration_count'), table_name='narrator')
    op.drop_index(op.f('ix_narrator_depth_spread'), table_name='narrator')
    op.drop_index(op.f('ix_narrator_canonical'), table_name='narrator')
    op.drop_table('narrator')
    # ### end Alembic commands ###
